# nginx proxy address - http://172.17.0.1:9000

name: sentry
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: getsentry/sentry:latest
    container_name: sentry-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
    ports:
      - '172.17.0.1:9000:9000'
    volumes:
      - './rootfs/data/sentry:/data'
    networks:
      - sentry

networks:
  sentry:
    name: sentry
    external: false
